eureka:
    instance:
        hostname: localhost
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:9093/eureka/
            
micro-services:
    company_service:
        base_url: lb://COMPANY-SERVICE/
        endpoints:
            endpoint:
                uri: http://COMPANY-SERVICE/company/getById/
    employee_service:
        base_url: lb://EMPLOYEE-SERVICE/
        endpoints:
            endpoint:
                uri: http://EMPLOYEE-SERVICE/employee/getAllByCompId/
            
            
