eureka:
    instance:
        prefer-ip-address: true
        hostname: eureka-0
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://eureka-0.eureka.default.svc.cluster.local:9093/eureka
            
micro-services:
    company_service:
        base_url: lb://COMPANY-SERVICE/
        endpoints:
            endpoint:
                uri: http://EMPLOYEE-SERVICE/employee/getAllByCompId/
        
            
            
